batch_size: 4
cond_disc: false
cuda: '0'
data_path: ../data/samples/metadata.csv
dataloader_num_workers: 1
downsamp_factor: 4
epochs: 3000
lambda_feat: 10
load_path: null
log_interval: 100
mode: mellotron
n_layers_D: 4
n_mel_channels: 80
n_residual_layers: 3
n_test_samples: 4
ndf: 16
ngf: 32
num_D: 3
ratios: 5 5 4 2
sample_rate: 16000
save_interval: 1000
save_path: ../models/melgan/samples
seq_len: 4800
start_step: 0
