attention_dim: 64
attention_location_kernel_size: 31
attention_location_n_filters: 16
attention_rnn_dim: 512
batch_size: 4
cmudict_path: null
cudnn_benchmark: false
cudnn_enabled: true
dataloader_num_workers: 2
decoder_rnn_dim: 512
dist_backend: nccl
dist_url: tcp://localhost:54321
distributed_run: false
dynamic_loss_scaling: true
encoder_embedding_dim: 256
encoder_kernel_size: 5
encoder_model_fpath: ../models/encoder/saved_models/ge2e_pretrained.pt
encoder_n_convolutions: 3
epochs: 1000000
f0_max: 880
f0_min: 80
filter_length: 1024
fp16_run: false
gate_threshold: 0.5
grad_clip_thresh: 1.0
harm_thresh: 0.25
hop_length: 256
ignore_layers:
- speaker_embedding.weight
iters_per_checkpoint: 100
learning_rate: 0.001
learning_rate_anneal: 50000
learning_rate_min: 1.0e-05
mask_padding: true
max_decoder_steps: 1000
max_wav_value: 32768.0
mel_fmax: 8000.0
mel_fmin: 0.0
n_frames_per_step: 1
n_mel_channels: 80
n_speakers: 32
n_symbols: 145
num_heads: 8
p_arpabet: 1.0
p_attention_dropout: 0.1
p_decoder_dropout: 0.1
p_teacher_forcing: 1.0
postnet_embedding_dim: 256
postnet_kernel_size: 5
postnet_n_convolutions: 5
prenet_dim: 128
prenet_f0_dim: 0
prenet_f0_kernel_size: 1
prenet_f0_n_layers: 1
prenet_rms_dim: 0
prenet_rms_kernel_size: 1
ref_enc_filters:
- 16
- 16
- 32
- 32
- 64
- 64
ref_enc_gru_size: 64
ref_enc_pad:
- 1
- 1
ref_enc_size:
- 3
- 3
ref_enc_strides:
- 2
- 2
sampling_rate: 22050
seed: 1234
speaker_embedding_dim: 32
symbols_embedding_dim: 256
text_cleaners: biaobei
token_embedding_size: 0
token_num: 10
train_mode: train-mspk
use_saved_learning_rate: false
weight_decay: 1.0e-06
win_length: 1024
with_gst: false
