abspath: E:/github-kuangdd/zhrtvc/data/samples/biaobei/wav/000020.wav
group_name: group_name
input_directory: ../data/samples/metadata.csv
learning_rate: 0.001
line: "biaobei/wav/000020.wav\t霍思燕露背秀乳沟性感惹火。\tbiaobei\n"
log_directory: tensorboard
meta_folder: ../models/mellotron/samples\metadata
n_gpus: 1
num: 49
out: "E:/github-kuangdd/zhrtvc/data/samples/biaobei/wav/000020.wav\t霍思燕露背秀乳沟性感惹火。\t\
  biaobei\n"
output_directory: ../models/mellotron/samples
rank: 0
speaker: biaobei
stem_path: ../models/mellotron/samples\metadata\locals
text: 霍思燕露背秀乳沟性感惹火。
trpath: ../models/mellotron/samples\metadata\train.txt
vapath: ../models/mellotron/samples\metadata\validation.txt
warm_start: false
